AWSTemplateFormatVersion: '2025-02-09'
Description: CloudFormation template to create an EC2 instance

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: ami-09a9858973b288bdd  # Replace with your desired AMI ID
      KeyName: MyKeyPair  # Replace with your key pair name
      SecurityGroups:
        - !Ref MySecurityGroup
      Tags:
        - Key: Name
          Value: CloudFormation-EC2

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: CloudFormation-SG
